# Generated by Django 2.2.6 on 2019-11-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20191111_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
