# Generated by Django 2.2.6 on 2019-11-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20191112_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(upload_to=''),
        ),
    ]
