# Generated by Django 2.2.6 on 2019-11-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20191112_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
