# Generated by Django 2.2.6 on 2019-11-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_auto_20191116_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.IntegerField(default=0),
        ),
    ]
