# Generated by Django 2.2.6 on 2019-11-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_auto_20191127_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
