# Generated by Django 2.2.6 on 2019-11-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('admin', '0004_auto_20191108_2339'),
        ('vendedor', '0002_auto_20191108_2339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
    ]
